  
  repository:
    image: "IMAGE_REGISTRY/repository:latest"
    links:
        - mongodb:mongodb
    command: ["grpc", "spaceone.repository", "-c", "/opt/repository.yml"]
    volumes:
      - ./conf/repository.yml:/opt/repository.yml

