GLOBAL:
    DATABASES:
        default:
            db: secret
            host: mongodb
            username: secret
            password: secret_password

    CACHES:
        default:
            backend: spaceone.core.cache.redis_cache.RedisCache
            host: redis 
            port: 6379
            db: 0

    CONNECTORS:
        AWSSecretManagerConnector:
            aws_access_key_id: AWS_ACCESS_KEY_ID
            aws_secret_access_key: AWS_SECRET_ACCESS_KEY
            region_name: REGION_NAME

        IdentityConnector:
          endpoint:
            v1: grpc://identity:50051

    HANDLERS:
        authentication:
        - backend: spaceone.core.handler.authentication_handler.AuthenticationGRPCHandler
          uri: grpc://identity:50051/v1/Domain/get_public_key

