
  supervisor:
    image: "IMAGE_REGISTRY/supervisor:latest"
    command: ["scheduler", "spaceone.supervisor", "-c", "/opt/supervisor.yml"]
    volumes:
      - ./conf/supervisor.yml:/opt/supervisor.yml
      - /var/run/docker.sock:/var/run/docker.sock:rw

    depends_on:
      - redis
