
  inventory-scheduler:
    image: "IMAGE_REGISTRY/inventory:latest"
    links:
        - mongodb:mongodb
        - redis:redis
    command: ["scheduler", "spaceone.inventory", "-c", "/opt/inventory.yml"]
    volumes:
      - ./conf/inventory.yml:/opt/inventory.yml
        #- ../../../:/opt/
    depends_on:
      - redis
      - identity
      - secret
      - repository
      - tester

